"""
Print the Caddy block for this app, derived from the public paths declared in
main.py.

The point is not to save typing. Public paths are declared in ONE place, in the
code, and the reverse-proxy block is read off that declaration — so the day
somebody adds a public route, they find out while writing it rather than after
deploying it.

    python caddy.py

Read the output before pasting it, and check the one thing this script cannot:
that no private route is a LONGER PREFIX of a public one. ArguMap had
`/api/maps/{id}/annotations` public and `/api/maps/{id}/annotations/detached`
private, and a rule written from the first would have opened the second.
"""
import re

from main import PUBLIC_PATHS

PORT = 8020
DOMAIN = "thelist.borant.eu"


def matcher(paths: list) -> str:
    return " ".join(paths)


def main() -> None:
    print(f"""\
# {DOMAIN} — TheList (port {PORT})
# Generated by caddy.py from PUBLIC_PATHS in main.py. Regenerate after adding
# any public route.
{DOMAIN} {{
    @pubbliche path {matcher(PUBLIC_PATHS)}

    # The machine surface never goes through the gate: it talks to programs, and
    # a redirect to a login page is the last thing an MCP client can handle.
    # Note the strict form — /mcp /mcp/* and not /mcp* — and that /mcp/* also
    # covers /mcp/k/{{key}}.
    handle /mcp /mcp/* {{ reverse_proxy localhost:{PORT} }}

    handle @pubbliche {{ import noforge; import nocookie; reverse_proxy localhost:{PORT} }}
    handle            {{ import borantid;                 reverse_proxy localhost:{PORT} }}
}}""")


if __name__ == "__main__":
    main()
