"""
Print the Caddy block for this app, derived from the public paths declared in
main.py.

The point is not to save typing. Public paths are declared in ONE place, in the
code, and the reverse-proxy block is read off that declaration — so the day
somebody adds a public route, they find out while writing it rather than after
deploying it.

    python caddy.py

Read the output before pasting it, and check the one thing this script cannot:
that no private route is a LONGER PREFIX of a public one. ArguMap had
`/api/maps/{id}/annotations` public and `/api/maps/{id}/annotations/detached`
private, and a rule written from the first would have opened the second.
"""
from main import MACHINE_PATHS, PUBLIC_PATHS

PORT = 8020
DOMAIN = "thelist.borant.eu"


def main() -> None:
    # One matcher for everything that skips the gate, public pages and machine
    # surface alike — the house form, and not only for tidiness: `noforge` is
    # what strips the X-Borant-* headers, and it is imported on this branch
    # only. A /mcp in a handle of its own would be a branch where a forged
    # identity header survives.
    #
    # Note the strict form: /mcp /mcp/* and never /mcp*. And /mcp/* covers
    # /mcp/k/{key}, the variant for clients that cannot set headers.
    paths = " ".join(PUBLIC_PATHS + MACHINE_PATHS)
    print(f"""\
# {DOMAIN} — TheList (port {PORT})
# Generated by caddy.py from PUBLIC_PATHS + MACHINE_PATHS in main.py.
# Regenerate after adding any route that must skip the gate.
{DOMAIN} {{
    @pubbliche path {paths}
    handle @pubbliche {{
        import noforge
        import nocookie
        reverse_proxy localhost:{PORT}
    }}
    handle {{
        import borantid
        reverse_proxy localhost:{PORT}
    }}
}}""")


if __name__ == "__main__":
    main()
